[[main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "about me"
    url = "/about"
    weight = 2

# [[main]]
#     identifier = "posts"
#     name = "posts"
#     url = "/posts"
#     weight = 3

[[main]]
    identifier = "tags"
    name = "tags"
    url = "/tags"
    weight = 3

# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "x"
    url = "https://x.com/gutek"
    weight = 1

[[social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/gutek"
    weight = 2
